name: Trigger auto deployment for azurefunday-capp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'application_codes/**'
    - '.github/workflows/azurefunday-capp-AutoDeployTrigger-44494a50-ad2e-46d1-84e7-5d1abee6b54a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: azurefundaydemoacr.azurecr.io
          username: ${{ secrets.AZUREFUNDAYCAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.AZUREFUNDAYCAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: azurefundaydemoacr.azurecr.io/covid-api:${{ github.sha }}
          file: ./application_codes/Dockerfile
          context: ./application_codes/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZUREFUNDAYCAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n azurefunday-capp -g AzureFundayDemo-RG --server azurefundaydemoacr.azurecr.io --username  ${{ secrets.AZUREFUNDAYCAPP_REGISTRY_USERNAME }} --password ${{ secrets.AZUREFUNDAYCAPP_REGISTRY_PASSWORD }}
            az containerapp update -n azurefunday-capp -g AzureFundayDemo-RG --image azurefundaydemoacr.azurecr.io/covid-api:${{ github.sha }}
